--------------------------------------------------------
--  DDL for Table DF_PRESUPUESTO_HISTORIAL
--------------------------------------------------------

  CREATE TABLE "BITACORA2"."DF_PRESUPUESTO_HISTORIAL" 
   (	"ID" NUMBER, 
	"CODPRESUPUESTO" NUMBER, 
	"USUARIO" VARCHAR2(20 BYTE), 
	"ELEMENTO_PEP" VARCHAR2(50 BYTE), 
	"PRESUPUESTO_USSD_OLD" NUMBER, 
	"PRESUPUESTO_USSD_NEW" NUMBER, 
	"PRESUPUESTO_COP_OLD" NUMBER, 
	"PRESUPUESTO_COP_NEW" NUMBER, 
	"FECHA_REGISTRO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DF_PRESUPUESTO_HISTORIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITACORA2"."DF_PRESUPUESTO_HISTORIAL_PK" ON "BITACORA2"."DF_PRESUPUESTO_HISTORIAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DF_PRESUPUESTO_HISTORIAL
--------------------------------------------------------

  ALTER TABLE "BITACORA2"."DF_PRESUPUESTO_HISTORIAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BITACORA2"."DF_PRESUPUESTO_HISTORIAL" ADD CONSTRAINT "DF_PRESUPUESTO_HISTORIAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DF_PRESUPUESTO_HISTORIAL
--------------------------------------------------------

  ALTER TABLE "BITACORA2"."DF_PRESUPUESTO_HISTORIAL" ADD CONSTRAINT "FK1UC8VN6MRE52PVBNV5JIN2BVV" FOREIGN KEY ("CODPRESUPUESTO")
	  REFERENCES "BITACORA2"."DF_PRESUPUESTO" ("ID") ENABLE;
