--------------------------------------------------------
--  DDL for Table DF_PRESUPUESTO
--------------------------------------------------------

  CREATE TABLE "BITACORA2"."DF_PRESUPUESTO" 
   (	"ID" NUMBER(10,0), 
	"CODEMPLEADOGERENTE" NUMBER(10,0), 
	"ELEMENTO_PEP" VARCHAR2(255 CHAR), 
	"FECHACREACION" TIMESTAMP (6), 
	"FECHAMODIFICACION" TIMESTAMP (6), 
	"POCISIONPRESUPUESTAL" VARCHAR2(255 CHAR), 
	"PRESUPUESTO_COP" NUMBER(19,2), 
	"PRESUPUESTO_USSD" NUMBER(19,2), 
	"SALDO_COP" NUMBER(19,2), 
	"SALDO_USSD" NUMBER(19,2), 
	"MODIFICADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITACORA2"."DF_PRESUPUESTO"."MODIFICADO" IS 'Identificador que diferencia presupuestos modificados (1) y no modificadon (0)';
--------------------------------------------------------
--  DDL for Index SYS_C0010551
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITACORA2"."SYS_C0010551" ON "BITACORA2"."DF_PRESUPUESTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DF_PRESUPUESTO
--------------------------------------------------------

  ALTER TABLE "BITACORA2"."DF_PRESUPUESTO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BITACORA2"."DF_PRESUPUESTO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
