--------------------------------------------------------
--  DDL for Table DF_EMPLEADOCONTROL
--------------------------------------------------------

  CREATE TABLE "BITACORA2"."DF_EMPLEADOCONTROL" 
   (	"ID" NUMBER(10,0), 
	"CODEMPLEADO" NUMBER(10,0), 
	"CODTAREA" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(255 CHAR), 
	"FECHACREACION" TIMESTAMP (6), 
	"FECHAHORAFIN" TIMESTAMP (6), 
	"FECHAHORAINICIO" TIMESTAMP (6), 
	"FECHAMODIFICACION" TIMESTAMP (6), 
	"HORAS" NUMBER(19,2), 
	"EXCEDIDO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BITACORA2"."DF_EMPLEADOCONTROL"."EXCEDIDO" IS 'Bandera para diferenciar horas que exceden un presupuesto (1) y las que no exceden un presupuesto (0)';
--------------------------------------------------------
--  DDL for Index SYS_C0010485
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITACORA2"."SYS_C0010485" ON "BITACORA2"."DF_EMPLEADOCONTROL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DF_EMPLEADOCONTROL
--------------------------------------------------------

  ALTER TABLE "BITACORA2"."DF_EMPLEADOCONTROL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BITACORA2"."DF_EMPLEADOCONTROL" ADD CHECK (codempleado>=1) ENABLE;
  ALTER TABLE "BITACORA2"."DF_EMPLEADOCONTROL" ADD CHECK (codtarea>=1) ENABLE;
  ALTER TABLE "BITACORA2"."DF_EMPLEADOCONTROL" ADD CHECK (horas>=1) ENABLE;
  ALTER TABLE "BITACORA2"."DF_EMPLEADOCONTROL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
