--------------------------------------------------------
-- Archivo creado  - lunes-junio-01-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DF_USUARIO_ROLES
--------------------------------------------------------

  CREATE TABLE "BITACORA2"."DF_USUARIO_ROLES" 
   (	"CODUSUARIO" NUMBER, 
	"CODUSUARIOROL" NUMBER, 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DF_USUARIO_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITACORA2"."DF_USUARIO_ROLES_PK" ON "BITACORA2"."DF_USUARIO_ROLES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DF_USUARIO_ROLES
--------------------------------------------------------

  ALTER TABLE "BITACORA2"."DF_USUARIO_ROLES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BITACORA2"."DF_USUARIO_ROLES" ADD CONSTRAINT "DF_USUARIO_ROLES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DF_USUARIO_ROLES
--------------------------------------------------------

  ALTER TABLE "BITACORA2"."DF_USUARIO_ROLES" ADD CONSTRAINT "DF_USUARIO_ROLES_FK1" FOREIGN KEY ("CODUSUARIO")
	  REFERENCES "BITACORA2"."DF_USUARIO" ("ID") ENABLE;
  ALTER TABLE "BITACORA2"."DF_USUARIO_ROLES" ADD CONSTRAINT "DF_USUARIO_ROLES_FK2" FOREIGN KEY ("CODUSUARIOROL")
	  REFERENCES "BITACORA2"."DF_USUARIOROL" ("ID") ENABLE;
