
  CREATE OR REPLACE FORCE VIEW "BITACORA2"."DF_EMPLEADO_VU" ("ID", "CODEMPLEADO", "CODPERSONA", "NOMBRE", "CODTIPODOCUMENTO", "TIPODOCUMENTO", "NUMERODOCUMENTO", "NOMBRE1", "NOMBRE2", "APELLIDO1", "APELLIDO2", "TELEFONO", "CORREO", "DIRECCIONRESIDENCIA", "GENERO", "GENERONOMBRE", "FECHANACIMIENTO", "CODPERFIL", "PERFIL", "CODPERFILTIPO", "PERFILTIPO", "CODLINEAPRODUCTO", "LINEAPRODUCTO", "CODPROVEEDOR", "PROVEEDOR", "CODPERFILNIVEL", "PERFILNIVEL", "USUARIOCLARO", "FECHAINICIO", "FECHAFIN", "CODESTRUCTURAORGANIZACIONAL") AS 
  SELECT 	ROWNUM ID,
			E.ID CODEMPLEADO,
            P.ID CODPERSONA,
			P.NOMBRE1 || ' ' || NVL(P.NOMBRE2, '') || ' ' || P.APELLIDO1 || ' ' || NVL(P.APELLIDO2, '') AS NOMBRE,
			P.CODTIPODOCUMENTO,
			TD.NOMBRE TIPODOCUMENTO,
			P.NUMERODOCUMENTO,
			P.NOMBRE1, 
			P.NOMBRE2,
			P.APELLIDO1,
			P.APELLIDO2,
			P.TELEFONO,
			P.CORREO,
			P.DIRECCIONRESIDENCIA,
			P.GENERO,
			CASE WHEN P.GENERO = 'M' THEN 'Masculino' 
				 WHEN P.GENERO = 'F' THEN 'Femenino' 
			END GENERONOMBRE,
			P.FECHANACIMIENTO,
			E.CODPERFIL,
			PR.NOMBRE PERFIL,
			E.CODPERFILTIPO,
			PT.NOMBRE PERFILTIPO,
			E.CODLINEAPRODUCTO,
			LP.NOMBRE LINEAPRODUCTO,
			E.CODPROVEEDOR,
			PV.NOMBRE PROVEEDOR,
			E.CODPERFILNIVEL,
			PN.NOMBRE PERFILNIVEL,
			E.USUARIOCLARO,
			E.FECHAINICIO,
			E.FECHAFIN,
            E.CODESTRUCTURAORGANIZACIONAL
	FROM DF_EMPLEADO E
    LEFT JOIN DF_PERSONA P ON P.ID = E.CODPERSONA
	LEFT JOIN DF_TIPODOCUMENTO TD ON TD.ID = P.CODTIPODOCUMENTO	
	LEFT JOIN DF_PERFIL PR ON PR.ID = E.CODPERFIL
	LEFT JOIN DF_PERFILTIPO PT ON PT.ID = E.CODPERFILTIPO
	LEFT JOIN DF_LINEASPRODUCTO LP ON LP.ID = E.CODLINEAPRODUCTO
	LEFT JOIN DF_PROVEEDOR PV ON PV.ID = E.CODPROVEEDOR
	LEFT JOIN DF_PERFILNIVEL PN ON PN.ID = E.CODPERFILNIVEL;
